name:  avl_tree
description: >
   An implementation of an AVL tree (a balanced binary search tree)

author: Karl Guggisberg <karl.guggisberg@guggis.ch>
version: 0.0.1

dev_dependencies:
  unittest: any
